# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImpactAnalysisAdministration
                                 A QGIS plugin
 QGIS 3 plugin for impact analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-19
        copyright            : (C) 2019 by Bo Victor Thomsen LIFA DK A/S
        email                : bvt@lifa.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImpactAnalysisAdministration class from file ImpactAnalysisAdministration.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .impact_analysis_administration import ImpactAnalysisAdministration
    return ImpactAnalysisAdministration(iface)
